# Generated by Django 5.2.6 on 2026-05-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                (
                    "triage_nivel",
                    models.CharField(
                        choices=[
                            ("ROJO", "Rojo (Nivel 1 - Crítico)"),
                            ("NARANJA", "Naranja (Nivel 2 - Emergencia)"),
                            ("AMARILLO", "Amarillo (Nivel 3 - Urgencia)"),
                            ("VERDE", "Verde (Nivel 4 - Menor)"),
                            ("AZUL", "Azul (Nivel 5 - No Urgente)"),
                        ],
                        default="AMARILLO",
                        max_length=20,
                        verbose_name="Nivel de Triage",
                    ),
                ),
                (
                    "motivo_consulta",
                    models.TextField(verbose_name="Motivo de Consulta"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_ESPERA", "En Espera de Triage"),
                            ("EN_TRIAJE", "En Triaje / Evaluación"),
                            ("ADMITIDO", "Admitido con Recurso"),
                            ("ALTA", "Dado de Alta / Egreso"),
                        ],
                        default="EN_ESPERA",
                        max_length=20,
                        verbose_name="Estado de la Admisión",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de Insumo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre de Insumo"),
                ),
                ("stock", models.IntegerField(verbose_name="Stock Disponible")),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Documento de Identidad",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "historia_clinica_num",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        verbose_name="Número de Historia Clínica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de Recurso",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CAMA", "Cama"),
                            ("BOX", "Box de Atención"),
                            ("QUIROFANO", "Quirófano"),
                        ],
                        default="CAMA",
                        max_length=20,
                        verbose_name="Tipo de Recurso",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADO", "Ocupado"),
                            ("MANTENIMIENTO", "En Mantenimiento"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuentaFacturacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cargado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Cargado",
                    ),
                ),
                (
                    "admision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_facturacion",
                        to="urgencias.admision",
                        verbose_name="Admisión",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoFacturacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "precio_aplicado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Aplicado"
                    ),
                ),
                (
                    "fecha_cargo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cargo"
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="urgencias.cuentafacturacion",
                        verbose_name="Cuenta de Facturación",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos_aplicados",
                        to="urgencias.insumo",
                        verbose_name="Insumo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admision",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admisiones",
                to="urgencias.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="recurso_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_activas",
                to="urgencias.recurso",
                verbose_name="Recurso Asignado",
            ),
        ),
    ]
