# Generated by Django 5.2.6 on 2026-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urgencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("OCUPADO", "Ocupado"),
                    ("MANTENIMIENTO", "En Mantenimiento"),
                    ("PRE_ALTA", "Pre-Alta"),
                    ("LIMPIEZA", "En Limpieza"),
                ],
                default="DISPONIBLE",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
