# Generated by Django 5.2.6 on 2026-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urgencias", "0002_alter_recurso_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="fecha_admision_cama",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Asignación de Cama"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="fecha_alta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Alta Definitiva"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="fecha_pre_alta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Orden de Pre-Alta"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="fecha_triage",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Evaluación Triage"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="notas_alta",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas de Egreso"
            ),
        ),
    ]
