# Generated by Django 5.2.6 on 2026-07-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0001_initial"),
        ("urgencias", "0003_admision_fecha_admision_cama_admision_fecha_alta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargofacturacion",
            name="medicamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos_aplicados",
                to="farmacia.medicamento",
                verbose_name="Medicamento",
            ),
        ),
        migrations.AlterField(
            model_name="cargofacturacion",
            name="insumo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos_aplicados",
                to="urgencias.insumo",
                verbose_name="Insumo",
            ),
        ),
    ]
