# Generated by Django 5.2.6 on 2026-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urgencias", "0004_cargofacturacion_medicamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="alergias_conocidas",
            field=models.TextField(
                blank=True, help_text="Alergias a medicamentos u otros.", null=True
            ),
        ),
    ]
