# Generated by Django 5.2.6 on 2026-07-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urgencias", "0005_paciente_alergias_conocidas"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="admision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ALTA"), _negated=True),
                fields=("recurso_asignado",),
                name="unique_active_admission_per_resource",
            ),
        ),
    ]
