# Generated by Django 5.2.6 on 2026-07-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0005_alter_receta_estado_alter_receta_fecha_emision_and_more"),
        ("urgencias", "0006_admision_unique_active_admission_per_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EN_ESPERA", "En Espera de Triage"),
                    ("EN_TRIAJE", "En Triaje / Evaluación"),
                    ("ADMITIDO", "Admitido con Recurso"),
                    ("ALTA", "Dado de Alta / Egreso"),
                ],
                db_index=True,
                default="EN_ESPERA",
                max_length=20,
                verbose_name="Estado de la Admisión",
            ),
        ),
        migrations.AddConstraint(
            model_name="admision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_alta__gte", models.F("fecha_ingreso")),
                    ("fecha_alta__isnull", True),
                    _connector="OR",
                ),
                name="admision_fechas_logicas",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargofacturacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="cargo_cantidad_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="cargofacturacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_aplicado__gte", 0)),
                name="cargo_precio_aplicado_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cuentafacturacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cargado__gte", 0)),
                name="cuenta_total_cargado_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="insumo",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="insumo_stock_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="insumo",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", 0)),
                name="insumo_precio_unitario_positive",
            ),
        ),
    ]
