# Generated by Django 5.2.6 on 2026-07-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("urgencias", "0003_admision_fecha_admision_cama_admision_fecha_alta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre Comercial"),
                ),
                (
                    "principio_activo",
                    models.CharField(max_length=150, verbose_name="Principio Activo"),
                ),
                (
                    "concentracion",
                    models.CharField(max_length=50, verbose_name="Concentración"),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventarioFarmacia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_actual",
                    models.IntegerField(default=0, verbose_name="Stock Actual"),
                ),
                (
                    "medicamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="farmacia.medicamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Despacho"),
                            ("DESPACHADA", "Despachada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_despacho", models.DateTimeField(blank=True, null=True)),
                (
                    "medico",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Médico Prescriptor",
                    ),
                ),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas_farmacia",
                        to="urgencias.admision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("indicaciones", models.TextField(blank=True, null=True)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="farmacia.medicamento",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="farmacia.receta",
                    ),
                ),
            ],
        ),
    ]
