# Generated by Django 5.2.6 on 2026-07-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0001_initial"),
        ("urgencias", "0005_paciente_alergias_conocidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("RUTINA", "Rutina"),
                    ("URGENTE", "Urgente"),
                    ("EMERGENCIA", "Emergencia / STAT"),
                ],
                default="RUTINA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="admision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recetas",
                to="urgencias.admision",
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("DESPACHADA", "Despachada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
