# Generated by Django 5.2.6 on 2026-07-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0002_receta_prioridad_alter_receta_admision_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventariofarmacia",
            name="stock_actual",
        ),
        migrations.AddField(
            model_name="inventariofarmacia",
            name="stock_comprometido",
            field=models.IntegerField(
                default=0, verbose_name="Stock Comprometido (En Recetas)"
            ),
        ),
        migrations.AddField(
            model_name="inventariofarmacia",
            name="stock_fisico",
            field=models.IntegerField(
                default=0, verbose_name="Stock Físico (Estantes)"
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("DESPACHADA", "Despachada"),
                    ("CANCELADA", "Cancelada"),
                    ("ADMINISTRADO_BOTIQUIN", "Administrado de Botiquín (Retroactivo)"),
                ],
                default="PENDIENTE",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BotiquinSatelite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        max_length=100, verbose_name="Ubicación (Ej. Carro Paro Box 3)"
                    ),
                ),
                (
                    "cantidad_fisica",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad Físico en Botiquín"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="botiquines",
                        to="farmacia.medicamento",
                    ),
                ),
            ],
        ),
    ]
