# Generated by Django 5.2.6 on 2026-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0003_remove_inventariofarmacia_stock_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="farmaceutico_despacho",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Farmacéutico que Despachó",
            ),
        ),
    ]
