# Generated by Django 5.2.6 on 2026-07-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0004_receta_farmaceutico_despacho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("DESPACHADA", "Despachada"),
                    ("CANCELADA", "Cancelada"),
                    ("ADMINISTRADO_BOTIQUIN", "Administrado de Botiquín (Retroactivo)"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="fecha_emision",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="botiquinsatelite",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_fisica__gte", 0)),
                name="botiquin_cantidad_fisica_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallereceta",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="detalle_receta_cantidad_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventariofarmacia",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_fisico__gte", 0)),
                name="inventario_stock_fisico_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventariofarmacia",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_comprometido__gte", 0)),
                name="inventario_stock_comprometido_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", 0)),
                name="medicamento_precio_unitario_positive",
            ),
        ),
    ]
